name: lunacd-megasync
title: MEGA Desktop App
base: core22
version: '6.4.0.2'
license: Proprietary
icon: gui/mega.png
summary: Easy automated syncing between your computers and your MEGA Cloud Drive
description: |
  Easy automated syncing and backup between your computers and your MEGA cloud drive.

  MEGA Desktop is an installable application that synchronises folders between your
  computer and your MEGA Cloud Drive. All files and subfolders will be replicated in
  both directions. Changes that you make on your device will also be made on the MEGA
  Cloud Drive. Similarly, changes made in your MEGA Cloud Drive (such as renaming,
  moving and deleting) will also be made to the synced folders on your device.

  Unofficial build of MEGA Desktop App. Not affiliated with, endorsed by, or supported by
  MEGA Limited.

website:
  - https://mega.io/desktop
source-code:
  - https://github.com/meganz/MEGAsync
  - https://github.com/lunacd/MEGAsync-snap
issues:
  - https://github.com/lunacd/MEGAsync-snap/issues
contact:
  - liu.haowen.andy@gmail.com

grade: stable
confinement: strict

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22
  mega-store:
    interface: personal-files
    write:
      - $HOME/.local/share/data/Mega Limited

layout:
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d

parts:
  libcurl:
    plugin: cmake
    source: https://github.com/curl/curl.git
    source-type: git
    source-tag: curl-8_21_0
    source-depth: 1
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_INSTALL_LIBDIR=/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR"
      - "--install-prefix /usr"
    build-packages:
      - libpsl-dev
    stage-packages:
      - libpsl5
    
  megasync:
    after:
      - libcurl

    plugin: cmake
    source: https://github.com/meganz/MEGAsync.git
    source-type: git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}_Linux
    source-depth: 1
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_MODULE_PATH=${CRAFT_PART_SRC}/src/MEGASync/mega/cmake/modules/packages"
      - "-DUSE_PDFIUM=OFF" # TODO
      - "-DUSE_BREAKPAD=OFF"
      - "-DENABLE_DESKTOP_UPDATE_GEN=OFF" # No need to update in snaps
      - "-DENABLE_DESKTOP_UPDATER=OFF" # No need to update in snaps
    cmake-generator: Ninja

    override-pull: |
      craftctl default
      git am "${CRAFT_PROJECT_DIR}/patches/0001-Avoid-native-file-chooser.patch"
      git am "${CRAFT_PROJECT_DIR}/patches/0002-Expose-socket-to-real-user-home.patch"
      git am "${CRAFT_PROJECT_DIR}/patches/0003-Use-real-home-in-snap.patch"

    override-build: |
      craftctl default

      # As of snapcraft 9.0, there's no support for resolving named icons:
      # https://github.com/canonical/snapcraft/blob/df4418f67617fcddb551f28d00d9004728cd1ff6/snapcraft/parts/desktop_file.py#L93
      cp $CRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/mega.png $CRAFT_PART_INSTALL/mega

    build-packages:
      - pkgconf
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libcrypto++-dev
      - libfreeimage-dev
      - libglib2.0-dev
      - libicu-dev
      - libmediainfo-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libsodium-dev
      - libswresample-dev
      - libswscale-dev
      - libuv1-dev

    stage-packages:
      - libavcodec58
      - libavformat58
      - libavutil56
      - libcrypto++8
      - libfreeimage3
      - libglib2.0-0
      - libmediainfo0v5
      - libsodium23
      - libswresample3
      - libswscale5
      - libuv1
      - libxcb1
      - libxcb-shape0
      - x11-xserver-utils

    stage:
      # Part of libglib2.0, this app doesn't use the threading part of glib
      - -usr/lib/*/libgthread-2.0.so*
      # Part of libicu, this app doesn't use those shared objects
      - -usr/lib/*/libicuio.so*
      - -usr/lib/*/libicutest.so*
      # OpenEXR is pulled in by FreeImage, but those parts are unused
      - -usr/lib/*/libOpenEXRCore-3_1.so*
      - -usr/lib/*/libOpenEXRUtil-3_1.so*
      - -usr/lib/*/libIlmImfUtil-2_5.so*
      # avcodec pulls in libjxl0.7, then libhwy, but those parts are unused
      - -usr/lib/*/libhwy_contrib.so*
      - -usr/lib/*/libhwy_test.so*
      # avcodec pulls in librist4, then libcjson1, but those parts are unused
      - -usr/lib/*/libcjson_utils.so*
      # avcodec pulls in libtheora0, but those parts are unused
      - -usr/lib/*/libtheora.so*
      # avcodec pulls in libmfx1, but those parts are unused
      - -usr/lib/*/libmfx-tracer.so*
      - -usr/lib/*/libmfxhw64.so*
      # avcodec pulls in libzvbi0t64, but those parts are unused
      - -usr/lib/*/libzvbi-chains.so*
      # FreeImage pulls in libraw23t64, but those parts are unused
      - -usr/lib/*/libraw_r.so*
      # FreeImage pull in libilmbase25, but those parts are unused
      - -usr/lib/*/libIexMath-2_5.so*

  graphics-core22:
    after: [megasync]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
    prime:
      - bin/graphics-core22-wrapper

apps:
  megasync:
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/megasync
    extensions:
      - kde-neon
    plugs:
      - home
      - mega-store
    desktop: usr/share/applications/megasync.desktop

lint:
  ignore:
    - library:
      # Dynamically loaded by Qt xcb plugin
      - usr/lib/*/libxcb-shape.so*
