name: lunacd-megasync
base: core22
version: '6.4.0.2'
license: 
summary: Easy automated syncing between your computers and your MEGA Cloud Drive
description: |
  Easy automated syncing and backup between your computers and your MEGA cloud drive.

  MEGA Desktop is an installable application that synchronises folders between your
  computer and your MEGA Cloud Drive. All files and subfolders will be replicated in
  both directions. Changes that you make on your device will also be made on the MEGA
  Cloud Drive. Similarly, changes made in your MEGA Cloud Drive (such as renaming,
  moving and deleting) will also be made to the synced folders on your device.

grade: devel
confinement: devmode

parts:
  pdfium:
    plugin: nil

  megasync:
    plugin: cmake
    source: https://github.com/meganz/MEGAsync.git
    source-type: git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}_Linux
    source-depth: 1
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
      - "-DCMAKE_MODULE_PATH=${CRAFT_PART_SRC}/src/MEGASync/mega/cmake/modules/packages"
      - "-DUSE_PDFIUM=OFF" # TODO
      - "-DUSE_BREAKPAD=OFF" # TODO
      - "-DENABLE_DESKTOP_UPDATE_GEN=OFF" # No need to update in snaps
      - "-DENABLE_DESKTOP_UPDATER=OFF" # No need to update in snaps
    cmake-generator: Ninja

    build-packages:
      - pkgconf
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libcurl3-gnutls-dev
      - libcrypto++-dev
      - libfreeimage-dev
      - libglib2.0-dev
      - libicu-dev
      - libmediainfo-dev
      - libqt5x11extras5-dev
      - libqt5svg5-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
      - libsodium-dev
      - libswresample-dev
      - libswscale-dev
      - libuv1-dev
      - locales
      - qtbase5-dev
      - qtdeclarative5-dev
      - qttools5-dev

    stage-packages:
      - libavcodec58
      - libavformat58
      - libavutil56
      - libcrypto++8
      - libcurl3-gnutls
      - libfreeimage3
      - libglib2.0-0
      - libicu70
      - libmediainfo0v5
      - libqt5x11extras5
      - libqt5svg5
      - libqt5qml5
      - libqt5qmlmodels5
      - libqt5quick5
      - libqt5quickwidgets5
      - libreadline8
      - libssl3
      - libsqlite3-0
      - libsodium23
      - libswresample3
      - libswscale5
      - libuv1
      - libxcb1
      - qml-module-qtgraphicaleffects
      - qml-module-qtqml-models2
      - qml-module-qtquick-controls
      - qml-module-qtquick-controls2
      - qml-module-qtquick-dialogs
      - qml-module-qtquick-layouts
      - qml-module-qtquick-templates2
      - qml-module-qtquick-window2
      - qml-module-qtquick2
      - x11-xserver-utils

    stage:
      # OpenEXR is pulled in by FreeImage, but those parts are unused
      - -usr/lib/*/libOpenEXRCore-3_1.so*
      - -usr/lib/*/libOpenEXRUtil-3_1.so*
      # Part of libglib2.0, this app doesn't use the threading part of glib
      - -usr/lib/*/libgthread-2.0.so*
      # avcodec pulls in libjxl0.7, then libhwy, but those parts are unused
      - -usr/lib/*/libhwy_contrib.so*
      - -usr/lib/*/libhwy_test.so*
      # avcodec pulls in librist4, then libcjson1, but those parts are unused
      - -usr/lib/*/libcjson_utils.so*
      # avcodec pulls in libtheora0, but those parts are unused
      - -usr/lib/*/libtheora.so*
      # avcodec pulls in libzvbi0t64, but those parts are unused
      - -usr/lib/*/libzvbi-chains.so*
      # FreeImage pulls in libraw23t64, but those parts are unused
      - -usr/lib/*/libraw_r.so*

apps:
  megasync:
    command: usr/bin/megasync
    extensions:
      - kde-neon
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - x11
      - wayland
      - gsettings
      - home
    environment:
      # QT_DEBUG_PLUGINS: 1
      # QML_IMPORT_TRACE: 1
      # QML_DISABLE_DISK_CACHE: 1
      # QT_LOGGING_RULES: "qt.qml.import.debug=true;qt.qml.plugin.debug=true;qt.qpa.plugin=true"
      QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins
      QML2_IMPORT_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/qml
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt5/plugins/platforms

